### LAYOUT ###
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/ElseAlignment:
  Enabled: false

### METRICS ###
Metrics/LineLength:
  Max: 100
Metrics/MethodLength:
  Max: 20
Metrics/AbcSize:
  Max: 20

### NAMING ###
Naming/PredicateName:
  Enabled: false

### STYLE ###
Style/NumericPredicate:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false
Style/EmptyMethod:
  EnforcedStyle: expanded
Layout/DotPosition:
  EnforcedStyle: trailing
Style/Documentation:
  Enabled: false
Style/ParenthesesAroundCondition:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
# TODO (bree.elle 2019-08-26): to be revised by 2019-01-01.
Style/RedundantSelf:
  Enabled: false
